# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'

target 'ApartmentManagement' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for ApartmentManagement

  target 'ApartmentManagementTests' do
    inherit! :search_paths
    # Pods for testing
  end
	
end

pod 'OneSignal', '~> 1.13.3'
pod 'RSKImageCropper’
pod 'QBImagePickerController'

